//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoOps.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        public int RaceId { get; set; }
        public Nullable<long> EventId { get; set; }
        public Nullable<long> RacerId { get; set; }
    }
}
